name: Build and Deploy generator

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *" # Runs at 08:00 UTC every day.

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          npm run generate

      - name: Generate data 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: templates # Folder you wish to deploy
          branch: main
          target-folder: templates
